export const userData = [
  { id: 1, name: "Jamal Kerrod", role: "Super Admin" },
  { id: 2, name: "Shamus Tuttle", role: "Super Admin" },
  { id: 3, name: "Devonne Wallbridge", role: "Content Admin" },
  { id: 4, name: "Ariella Filippyev", role: "Content Admin" },
  { id: 5, name: "Lutero Aloshechkin", role: "Curator" },
  { id: 6, name: "Raynell Clendennen", role: "Admin" },
  { id: 7, name: "Lorine Hischke", role: "Curator" },
  { id: 8, name: "Megan Espinoza", role: "Admin" },
  { id: 9, name: "Brett Dawson", role: "Curator" },
  { id: 10, name: "Sabina Herrera", role: "Content Admin" },
  { id: 11, name: "Philip Ward", role: "Admin" },
  { id: 12, name: "Francesca Allen", role: "Curator" },
  { id: 13, name: "Tobias Romero", role: "Content Admin" },
  { id: 14, name: "Camilla Sutton", role: "Admin" },
  { id: 15, name: "Diego Mathis", role: "Curator" },
  { id: 16, name: "Dina Rogers", role: "Content Admin" },
  { id: 17, name: "Juan Fisher", role: "Admin" },
  { id: 18, name: "Helene Duncan", role: "Curator" },
  { id: 19, name: "Clyde Stevens", role: "Content Admin" },
  { id: 20, name: "Ava Gallagher", role: "Super Admin" },
  { id: 21, name: "Raymond Marsh", role: "Admin" },
  { id: 22, name: "Keira Holmes", role: "Curator" },
  { id: 23, name: "Sophie Page", role: "Content Admin" },
  { id: 24, name: "Nathan Booth", role: "Curator" },
  { id: 25, name: "Leo Morrison", role: "Admin" },
  { id: 26, name: "Jodie Graham", role: "Content Admin" },
  { id: 27, name: "Harold Owens", role: "Admin" },
  { id: 28, name: "Estelle Poole", role: "Curator" },
  { id: 29, name: "Tommy Hill", role: "Content Admin" },
  { id: 30, name: "Alina Bates", role: "Admin" },
  { id: 31, name: "Frederic Cole", role: "Curator" },
  { id: 32, name: "Lily Price", role: "Content Admin" },
  { id: 33, name: "Adrian Cox", role: "Admin" },
  { id: 34, name: "Nicole Gray", role: "Curator" },
  { id: 35, name: "Marc Summers", role: "Content Admin" },
  { id: 36, name: "Rosie Miller", role: "Admin" },
  { id: 37, name: "Jordan Cooke", role: "Curator" },
  { id: 38, name: "Sienna King", role: "Content Admin" },
  { id: 39, name: "Aaron Edwards", role: "Admin" },
  { id: 40, name: "Daphne Nelson", role: "Curator" },
  { id: 41, name: "Luke Knight", role: "Content Admin" },
  { id: 42, name: "Isla Scott", role: "Admin" },
  { id: 43, name: "Peter Bell", role: "Curator" },
  { id: 44, name: "Emily Hughes", role: "Content Admin" },
  { id: 45, name: "Kurt Russell", role: "Admin" },
  { id: 46, name: "Mia Carter", role: "Curator" },
  { id: 47, name: "Oscar Bennett", role: "Content Admin" },
  { id: 48, name: "Lara Kelly", role: "Admin" },
  { id: 49, name: "Daniel Ford", role: "Curator" },
  { id: 50, name: "Hazel West", role: "Content Admin" },
];
