export const mockNotifications = [
  {
    id: "1",
    type: "critical",
    message: "Your business license will expire in 15 days",
    time: "2023-10-15T09:30:00",
    read: false,
    actionUrl: "/document_wallet",
    category: "Documents",
  },
  {
    id: "2",
    type: "message",
    message:
      "New message from ADGM Support Team regarding your service request",
    time: "2023-10-14T14:45:00",
    read: false,
    actionUrl: "/service_requests",
    category: "Messages",
  },
  {
    id: "3",
    type: "update",
    message: "Your service request SR-2023-1045 has been approved",
    time: "2023-10-14T11:20:00",
    read: true,
    actionUrl: "/service_requests",
    category: "Service Requests",
  },
  {
    id: "4",
    type: "critical",
    message: "Action required: Complete your annual compliance report",
    time: "2023-10-13T16:15:00",
    read: false,
    actionUrl: "/profile",
    category: "Compliance",
  },
  {
    id: "5",
    type: "update",
    message: "New industry regulations have been published",
    time: "2023-10-12T10:00:00",
    read: true,
    actionUrl: "/document_wallet",
    category: "Documents",
  },
  {
    id: "6",
    type: "message",
    message: "Your document 'Financial Statement 2023' has been reviewed",
    time: "2023-10-11T13:30:00",
    read: true,
    actionUrl: "/document_wallet",
    category: "Documents",
  },
  {
    id: "7",
    type: "update",
    message: "System maintenance scheduled for October 20, 2023",
    time: "2023-10-10T09:15:00",
    read: true,
    actionUrl: "#",
    category: "System",
  },
  {
    id: "8",
    type: "message",
    message: "New training resources available for enterprise users",
    time: "2023-10-09T15:45:00",
    read: true,
    actionUrl: "/support",
    category: "Training",
  },
  {
    id: "9",
    type: "critical",
    message: "Security alert: Your account was accessed from a new device",
    time: "2023-10-08T07:30:00",
    read: true,
    actionUrl: "/settings",
    category: "Security",
  },
  {
    id: "10",
    type: "update",
    message: "Your profile information has been updated successfully",
    time: "2023-10-07T16:20:00",
    read: true,
    actionUrl: "/profile",
    category: "Settings",
  },
];
