apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qatalyst-tech-tls
  namespace: staging
spec:
  secretName: qatalyst-tech-tls
  dnsNames:
    - qatalyst.tech
    - www.qatalyst.tech
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
